### ISSUE TITLE
New concept of columns for version 2.0

### ISSUE THREAD

**Issue by Tigrov** [yiisoft/db#854]
Main changes:

- [ ] 1. Remove `ColumnSchema::$name` and `ColumnSchema::$precision` (use `ColumnSchema::$size`) **(under discussion)**
- [ ] 2. Rename `ColumnSchema::$enumValues` to `ColumnSchema::$values` (related with some issues) **(under discussion)**
- [ ] 3. Add `ColumnSchema::getFullDbType()` method to get full name of the type, e.g. `varchar(20)` #695
- [ ] 4. Remove `pk` abstract type constants `ColumnSchemaInterface::...pk` use `ColumnBuilder::...pk()` instead yiisoft/db-migration#6
- [ ] 5. Rename `AbstractColumnSchema` to `Column`
- [ ] 6. Realize `TypeColumn` classes (`IntegerColumn`, `StringColumn`, etc) #752
- [ ] 7. Realize `ColumnFactory`, `ColumnBuilder` and `ColumnDefinitionBuilder`
- [ ] 8. Add constructor to `TableSchema` (instead of `AbstractSchema::resolveTableName()`)

The changes will solve few issues and after related improvements it will solve few more issues.
It will allow specify any php type or object type for any db type or table column.

There is a draft #808
